<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Oleumetry.UseCases\Oleumetry.UseCases.csproj" />
    <ProjectReference Include="..\Oleumetry.Postgres\Oleumetry.Postgres.csproj" />
    <ProjectReference Include="..\Oleumetry.RabbitMq\Oleumetry.RabbitMq.csproj" />
    <ProjectReference Include="..\Oleumetry.Redis\Oleumetry.Redis.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
