<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Oleumetry.WorkerTier-9f4cb33c-2702-488f-8be4-4812b28632c8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Oleumetry.UseCases\Oleumetry.UseCases.csproj" />
    <ProjectReference Include="..\Oleumetry.Postgres\Oleumetry.Postgres.csproj" />
    <ProjectReference Include="..\Oleumetry.RabbitMq\Oleumetry.RabbitMq.csproj" />
    <ProjectReference Include="..\Oleumetry.Emqx\Oleumetry.Emqx.csproj" />
    <ProjectReference Include="..\Oleumetry.Redis\Oleumetry.Redis.csproj" />
  </ItemGroup>
</Project>
